#!/bin/sh
set -e

export PATH=/bin
# Top secret option...
export DOCKER_RAMDISK=true

mount -t devtmpfs devtmpfs /dev

#mkdir /etc
mkdir /proc
mkdir /sys
mkdir /rw
mkdir -p /var/lib/docker
mkdir -p /var/run
mkdir -p /dev/pts

mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /sys/fs/cgroup
mount -t devpts devpts /dev/pts

for i in perf_event net_cls freezer devices blkio memory cpuacct cpu cpuset; do
    mkdir -p /sys/fs/cgroup/$i
    mount -t cgroup -o $i none /sys/fs/cgroup/$i
done

if ! mount /dev/sda /var/lib/docker; then
    echo "Running from memory, this won't be good..."
    export IN_MEMORY=true
    sleep 2
fi

modprobe overlay
modprobe e1000

echo 'nameserver 8.8.8.8' > /etc/resolv.conf

openvt /bin/sh
openvt -s /bin/console-container.sh

exec docker -d -D -s overlay
